# roboview 配置
# 产品信息
product: lrs-x
platform: nx
robot_type: lrs-x

# 机器人信息
motor_count: 26

# 话题订阅（可选话题置空则不订阅）
topic_state: /system/current_state
topic_motor_health: /motor_control/motor_health
topic_motor_feedback: /motor_control/motor_comand_feedback
topic_imu: /imu/data
topic_sensor_status:
topic_monitor: /system/resource_monitor
topic_joy_enabled: /iot_joy_enabled
topic_mapping_map: /map2d/mapping_map
topic_laserscan: /scan

# 广播限频：最小广播间隔（ms）
motor_health_interval: 1000
motor_action_feedback_interval: 200
imu_interval: 1000
monitor_interval: 1000
maps_broadcast_interval_ms: 500
maps_laserscan_broadcast_interval_ms: 500

# 路径配置（留空则使用代码内生产环境默认值）
joy_config_path: /data/joy_config.yaml
action_script_path: /app/etc/motor_state_publisher/config
local_maps_path: /root/maps
local_logs_path: /data/bigdata/lyoslog
local_bags_path: /data/bigdata/lyosbag
