# roboview 配置
# 产品信息
product: lrd-w
platform: rk3588
robot_type: lrd-w

# 机器人信息
motor_count: 16

# 话题订阅（可选话题置空则不订阅）
topic_state: /system/current_state
topic_motor_health: /motor_control/motor_health
topic_motor_feedback: /motor_control/motor_comand_feedback
topic_imu: /imu/data
topic_sensor_status:  # 预留，默认不订阅
topic_monitor: /system/resource_monitor
topic_joy_enabled: /iot_joy_enabled
topic_mapping_map: /map2d/mapping_map
topic_laserscan: /scan  # 预留 LaserScan
topic_nav_global_path: /planner_server/plan # 全局路径
topic_nav_teb_path: /controller_server/local_trajectory # 局部路径

# 广播限频：最小广播间隔（ms）
motor_health_interval: 1000
motor_action_feedback_interval: 200
imu_interval: 1000
monitor_interval: 1000
maps_broadcast_interval_ms: 500
maps_laserscan_broadcast_interval_ms: 500
maps_path_broadcast_interval_ms: 500
# process_interval: 1000
# sensor_status_interval: 1000

# 路径配置（留空则使用代码内生产环境默认值）
joy_config_path: /data/joy_config.yaml
action_script_path: /app/etc/motor_state_publisher/config
local_maps_path: /root/maps
local_logs_path: /data/bigdata/lyoslog
local_bags_path: /data/bigdata/lyosbag
